### PR TITLE
added Chinese translation

### PR DESCRIPTION
**Pull request by NeverMin**
please merge it. thanks.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Thanks Never! I'll create a new package version tomorrow.

**Comment by NeverMin** [comment]
Thanks Thorsten, :+1:

**Comment by thorsteneckel** [comment]
Package created. Have fun :)

**Comment by NeverMin** [comment]
Hi Thorsten,

i can't find translation file in the package, version is v1.5.3 right?
same to Znuny4OTRS-EscalationSuspend v2.1.2,
can you check again? thanks.


-Never

2015-05-28 15:51 GMT+08:00 Thorsten <notifications@github.com>:

**Pull request merged**
